In [1]:
# Importing the necessary libraries and csv file
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model as linm

# Import prepering data

df = pd.read_csv("ks_data/ks_projects_201801_preper.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378661 entries, 0 to 378660
Data columns (total 18 columns):
Unnamed: 0           378661 non-null int64
ID                   378661 non-null int64
name                 378661 non-null object
category             378661 non-null object
main_category        378661 non-null object
currency             378661 non-null object
deadline             378661 non-null object
goal                 378661 non-null float64
launched             378661 non-null object
pledged              378661 non-null float64
state                378661 non-null object
backers              378661 non-null int64
country              378661 non-null object
usd_pledged          378661 non-null object
usd_pledged_real     378661 non-null float64
usd_goal_real        378661 non-null float64
launched_week_day    378661 non-null object
duration             378661 non-null int64
dtypes: float64(4), int64(4), object(10)
memory usage: 52.0+ MB

In [4]:
# dataset description
df.describe()

,Unnamed: 0,ID,goal,pledged,backers,usd_pledged_real,usd_goal_real,duration
count,378661.000000,3.786610e+05,3.786610e+05,3.786610e+05,378661.000000,3.786610e+05,3.786610e+05,378661.000000
mean,189330.000000,1.074731e+09,4.908079e+04,9.682979e+03,105.617476,9.058924e+03,4.545440e+04,33.481122
std,109310.159478,6.190862e+08,1.183391e+06,9.563601e+04,907.185035,9.097334e+04,1.152950e+06,65.909172
min,0.000000,5.971000e+03,1.000000e-02,0.000000e+00,0.000000,0.000000e+00,1.000000e-02,0.000000
25%,94665.000000,5.382635e+08,2.000000e+03,3.000000e+01,2.000000,3.100000e+01,2.000000e+03,29.000000
50%,189330.000000,1.075276e+09,5.200000e+03,6.200000e+02,12.000000,6.243300e+02,5.500000e+03,29.000000
75%,283995.000000,1.610149e+09,1.600000e+04,4.076000e+03,56.000000,4.050000e+03,1.550000e+04,36.000000
max,378660.000000,2.147476e+09,1.000000e+08,2.033899e+07,219382.000000,2.033899e+07,1.663614e+08,16738.000000

Exploratory Data Analysis:
- dependence of the success of the campaign on the country
- dependence of the success of the campaign on the duration
- dependence of the success of the campaign on the category